-- 특정 형질을 가지는 대장균 찾기(301646) - Lv.1
SELECT COUNT(ID) AS COUNT
FROM ECOLI_DATA
WHERE !(GENOTYPE & 2) AND (GENOTYPE & 1 OR GENOTYPE & 4);  -- 비트 연산 시 3번째 형질을 나타내는 비트는 100(2), 4(10)임에 유의



-- 가장 큰 물고기 10마리 구하기(298517) - Lv.1
SELECT ID, LENGTH
FROM FISH_INFO
WHERE LENGTH IS NOT NULL
ORDER BY LENGTH DESC, ID
LIMIT 10;



-- 한 해에 잡은 물고기 수 구하기(298516) - Lv.1
SELECT COUNT(ID) AS FISH_COUNT
FROM FISH_INFO
WHERE DATE_FORMAT(TIME, '%Y') = 2021;



-- 잡은 물고기 중 가장 큰 물고기의 길이 구하기(298515) - Lv.1
SELECT CONCAT(MAX(LENGTH), 'cm') AS MAX_LENGTH
FROM FISH_INFO;



-- 잡은 물고기의 평균 길이 구하기(293259) - Lv.1
SELECT ROUND(AVG(IFNULL(LENGTH, 10)), 2) AS AVERAGE_LENGTH
FROM FISH_INFO;