-- 디지털 온보딩 연수 코테 대비 문제 풀이


-- KIT #JOIN 


-- 조건에 맞는 도서와 저자 리스트 출력하기
SELECT B.BOOK_ID, A.AUTHOR_NAME, B.PUBLISHED_DATE
FROM BOOK AS B INNER JOIN AUTHOR AS A ON B.AUTHOR_ID = A.AUTHOR_ID
WHERE B.CATEGORY = '경제'
ORDER BY B.PUBLISHED_DATE ASC;



-- 그룹별 조건에 맞는 식당 목록 출력하기
WITH HEAVY_REVIEWER AS (
    SELECT MEMBER_ID, RANK() OVER (ORDER BY COUNT(*) DESC) AS RANKING
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
)
-- 1) FROM / JOIN  ->  2) WHERE  ->  3) GROUP BY  ->  4) HAVING  ->  5) SELECT  -> 6) ORDER BY / LIMIT
-- 윈도우함수 RANK()는 4단계 종료 이후 수행이 되므로 CTE에서는 사용 불가함

SELECT M.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE AS M INNER JOIN REST_REVIEW AS R ON M.MEMBER_ID = R.MEMBER_ID
WHERE M.MEMBER_ID IN (SELECT MEMBER_ID FROM HEAVY_REVIEWER WHERE RANKING = 1)  -- 그래서 서브쿼리로 순위검증
ORDER BY R.REVIEW_DATE ASC, R.REVIEW_TEXT ASC;



-- 주문량이 많은 아이스크림들 조회하기
SELECT T.FLAVOR
FROM (SELECT * FROM FIRST_HALF UNION ALL SELECT * FROM JULY) AS T
GROUP BY T.FLAVOR
ORDER BY SUM(T.TOTAL_ORDER) DESC
LIMIT 3;



-- 특정 기간동안 대여 가능한 자동차들의 대여비용 구하기
SELECT C.CAR_ID, C.CAR_TYPE, FLOOR(C.DAILY_FEE*30*(100-P.DISCOUNT_RATE) / 100) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS C INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P ON C.CAR_TYPE = P.CAR_TYPE
WHERE C.CAR_TYPE IN ('세단', 'SUV') 
    AND P.DURATION_TYPE = '30일 이상' 
    AND C.CAR_ID NOT IN (
        SELECT CAR_ID 
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H 
        WHERE H.END_DATE >= '2022-11-01' AND H.START_DATE <= '2022-11-30'
    )  
GROUP BY C.CAR_ID, C.CAR_TYPE HAVING FEE >= 500000 AND FEE < 2000000  -- HAVING 안 쓸거면 FLOOR(~) 계산식을 WHERE에 넣고 비교해야함
ORDER BY FEE DESC, C.CAR_TYPE ASC, C.CAR_ID DESC;

-- another verion
SELECT C.CAR_ID, C.CAR_TYPE, FLOOR(C.DAILY_FEE * 30 * (100 - P.DISCOUNT_RATE) / 100) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS C
INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P ON C.CAR_TYPE = P.CAR_TYPE
LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H ON C.CAR_ID = H.CAR_ID
WHERE C.CAR_TYPE IN ('세단', 'SUV') AND P.DURATION_TYPE = '30일 이상'
GROUP BY C.CAR_ID, C.CAR_TYPE 
HAVING SUM(CASE WHEN H.START_DATE <= '2022-11-30' AND H.END_DATE >= '2022-11-01' THEN 1 ELSE 0 END) = 0
    AND FEE BETWEEN 500000 AND 1999999 
-- 서브쿼리 안 쓰고 비교하려면 LEFT JOIN하고 Having에 CASE WHEN 쓸 수 있음. BUT H는 여기만 쓰이는데 JOIN하면 오히려 결과 누락될 가능성도 있음.
ORDER BY FEE DESC, C.CAR_TYPE ASC, C.CAR_ID DESC;



-- 5월 식품들의 총매출 조회하기
SELECT P.PRODUCT_ID, P.PRODUCT_NAME, SUM(O.AMOUNT) * P.PRICE AS TOTAL_SALES
FROM FOOD_PRODUCT AS P INNER JOIN FOOD_ORDER AS O ON P.PRODUCT_ID = O.PRODUCT_ID
WHERE O.PRODUCE_DATE BETWEEN '2022-05-01' AND '2022-05-31'
GROUP BY P.PRODUCT_ID, P.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, P.PRODUCT_ID ASC;



-- 없어진 기록 찾기
SELECT O.ANIMAL_ID, O.NAME
FROM ANIMAL_INS AS I RIGHT JOIN ANIMAL_OUTS AS O ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE I.ANIMAL_ID IS NULL;



-- 있었는데요 없었습니다
SELECT O.ANIMAL_ID, O.NAME
FROM ANIMAL_INS AS I INNER JOIN ANIMAL_OUTS AS O ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE I.DATETIME > O.DATETIME
ORDER BY I.DATETIME ASC;



-- 오랜 기간 보호한 동물(1)
SELECT I.NAME, I.DATETIME
FROM ANIMAL_INS AS I LEFT JOIN ANIMAL_OUTS AS O ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE O.ANIMAL_ID IS NULL
ORDER BY I.DATETIME ASC
LIMIT 3;



-- 보호소에서 중성화한 동물
SELECT O.ANIMAL_ID, O.ANIMAL_TYPE, O.NAME
FROM ANIMAL_INS AS I INNER JOIN ANIMAL_OUTS AS O ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE I.SEX_UPON_INTAKE LIKE 'Intact%' AND O.SEX_UPON_OUTCOME NOT LIKE 'Intact%'
ORDER BY O.ANIMAL_ID ASC;



-- 상품 별 오프라인 매출 구하기
SELECT P.PRODUCT_CODE, SUM(P.PRICE * O.SALES_AMOUNT)AS SALES
FROM PRODUCT AS P INNER JOIN OFFLINE_SALE AS O ON P.PRODUCT_ID = O.PRODUCT_ID
GROUP BY P.PRODUCT_CODE
ORDER BY SALES DESC, P.PRODUCT_CODE ASC;



-- 상품을 구매한 회원 비율 구하기
SELECT YEAR(O.SALES_DATE) AS YEAR,
    MONTH(O.SALES_DATE) AS MONTH,
    COUNT(DISTINCT O.USER_ID) AS PURCHASED_USERS,
    ROUND(
        COUNT(DISTINCT O.USER_ID) /
        (SELECT COUNT(*) FROM USER_INFO WHERE YEAR(JOINED) = 2021)  -- 서브쿼리 안 쓰면 >> 2021년에 가입한 회원 중 << 분모 조건 미성립
    , 1) AS PUCHASED_RATIO
FROM USER_INFO AS U INNER JOIN ONLINE_SALE AS O ON U.USER_ID = O.USER_ID
WHERE YEAR(U.JOINED) = 2021  -- U.JOINED LIKE '2021%' 등 DATE 타입에도 LIKE사용 가능
GROUP BY YEAR, MONTH
ORDER BY YEAR ASC, MONTH ASC;



-- FrontEnd 개발자 찾기
SELECT DISTINCT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME  
FROM DEVELOPERS AS D INNER JOIN SKILLCODES AS S ON D.SKILL_CODE & S.CODE 
WHERE S.CATEGORY = 'Front End'
ORDER BY ID ASC;

-- SELECT DISTINCT : [column1, column2, column3, ..., columnN] N개의 칼럼 값이 모두 일치할 때 중복 제거
-- 한 개발자가 프론트엔드 스킬을 여러 개 가지고 있어도 ID | EMAIL | FIRST_NAME | LAST_NAME 은 동일하므로 중복 제거 요함

-- S.CODE(스킬코드)는 비트로 구분될 수 있게끔 2의 제곱수로 구성되어 있음.
-- D.SKILL_CODE = 400(110010000) 이라면?  256(100000000) + 128(10000000) + 16(10000) 총 3개의 스킬 보유
-- S.CODE 스킬을 보유하고 있다면 비트연산자 &를 사용했을 때 보유한 스킬만 JOIN됨. (서브쿼리 등 불필요)





-- KIT #GROUP_BY


-- 자동차 대여 기록에서 대여중 / 대여 가능 여부 구분하기
SELECT CAR_ID, 
    MAX(IF('2022-10-16' BETWEEN START_DATE AND END_DATE, '대여중', '대여 가능')) AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
ORDER BY CAR_ID DESC;

-- 그냥 IF는 그룹 내 전체 행을 탐색하지 않지만, 집계함수 MAX()를 사용하면 문자열 크기가 비교됨 ['대여중' > '대여 가능']
-- 하나라도 '대여중'이면 AVAILABILITY = '대여중', 모두 '대여 가능'인 경우에만 AVAILABILITY = '대여 가능'



-- 저자 별 카테고리 별 매출액 집계하기
SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(S.SALES * PRICE) AS TOTAL_SALES
FROM BOOK_SALES AS S 
INNER JOIN BOOK AS B ON S.BOOK_ID = B.BOOK_ID
INNER JOIN AUTHOR AS A ON B.AUTHOR_ID = A.AUTHOR_ID
WHERE S.SALES_DATE LIKE '2022-01%'
GROUP BY A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY
ORDER BY A.AUTHOR_ID ASC, B.CATEGORY DESC;



-- 부서별 평균 연봉 조회하기
SELECT D.DEPT_ID, D.DEPT_NAME_EN, ROUND(AVG(E.SAL), 0) AS AVG_SAL
FROM HR_DEPARTMENT AS D INNER JOIN HR_EMPLOYEES AS E ON D.DEPT_ID = E.DEPT_ID
GROUP BY D.DEPT_ID, D.DEPT_NAME_EN
ORDER BY AVG_SAL DESC;



-- 연간 평가점수에 해당하는 평가 등급 및 성과금 조회하기
SELECT E.EMP_NO, 
    E.EMP_NAME,
    CASE 
        WHEN AVG(G.SCORE) >= 96 THEN 'S'
        WHEN AVG(G.SCORE) >= 90 THEN 'A'
        WHEN AVG(G.SCORE) >= 80 THEN 'B'
        ELSE 'C'
    END AS GRADE,
    CASE 
        WHEN AVG(G.SCORE) >= 96 THEN E.SAL * 0.2
        WHEN AVG(G.SCORE) >= 90 THEN E.SAL * 0.15
        WHEN AVG(G.SCORE) >= 80 THEN E.SAL * 0.1
        ELSE 0
    END AS BONUS
FROM HR_EMPLOYEES AS E INNER JOIN HR_GRADE AS G ON E.EMP_NO = G.EMP_NO
GROUP BY E.EMP_NO, E.EMP_NAME
ORDER BY E.EMP_NO ASC;



-- 식품분류별 가장 비싼 식품의 정보 조회하기
SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT
WHERE (CATEGORY, PRICE) IN (
    SELECT CATEGORY, MAX(PRICE)
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
    GROUP BY CATEGORY
)
ORDER BY MAX_PRICE DESC;

-- 공동 1위까지 처리하려면 윈도우 함수 RANK() 사용이 효과적
SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
FROM (
    SELECT CATEGORY, PRICE, PRODUCT_NAME, 
        RANK() OVER(PARTITION BY CATEGORY ORDER BY PRICE DESC) AS RANKING  -- GROUP BY 쓰면 안 되니까(NAME 유실) PARTITION BY
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유') 
) AS T
WHERE RANKING = 1
ORDER BY MAX_PRICE DESC;



-- 즐겨찾기가 가장 많은 식당 정보 출력하기
WITH RANKING AS (
    SELECT *, RANK() OVER(PARTITION BY FOOD_TYPE ORDER BY FAVORITES DESC) AS FAV_RANKS
    FROM REST_INFO
)

SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM RANKING
WHERE FAV_RANKS = 1
ORDER BY FOOD_TYPE DESC;



-- 자동차 종류 별 특정 옵션이 포함된 자동차 수 구하기
SELECT CAR_TYPE, COUNT(*) AS CARS
FROM CAR_RENTAL_COMPANY_CAR
WHERE OPTIONS LIKE '%통풍시트%'
    OR OPTIONS LIKE '%열선시트%'
    OR OPTIONS LIKE '%가죽시트%'
GROUP BY CAR_TYPE
ORDER BY CAR_TYPE ASC;



-- 카테고리 별 도서 판매량 집계하기
SELECT B.CATEGORY, SUM(S.SALES) AS TOTAL_SALES
FROM BOOK AS B INNER JOIN BOOK_SALES AS S ON B.BOOK_ID = S.BOOK_ID
WHERE S.SALES_DATE LIKE '2022-01%'
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY ASC;



-- 대여 횟수가 많은 자동차들의 월별 대여 횟수 구하기
SELECT MONTH, CAR_ID, RECORDS 
FROM (
    SELECT DISTINCT MONTH(START_DATE) AS MONTH, CAR_ID,  -- OVER(윈도우함수) 쓰면 중복 제거 X.(기존 행에 칼럼만 추가)
        COUNT(*) OVER(PARTITION BY CAR_ID) AS CAR_TOTAL
        COUNT(*) OVER(PARTITION BY MONTH(START_DATE), CAR_ID) AS RECORDS
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
) AS T
WHERE CAR_TOTAL >= 5 AND RECORDS > 0  -- WHERE 서브쿼리로 일치하는 자동차ID를 거른다면 어차피 내부+외부 다 GROUP BY+HAVING에서 개수 필터링
-- GROUP BY MONTH, CAR_ID   -- 바깥에서 GROUP BY를 한 번 더 쓰거나, 서브쿼리 내에서 DISTINCT 사용 등 중복제거 요함.(상황별 성능 차이)
ORDER BY MONTH ASC, CAR_ID DESC;



-- 입양 시각 구하기(2)
SET @HOUR := -1;             -- SET @Variable :=(할당연산자) N;   MySQL 변수 설정 방법

SELECT (@HOUR := @HOUR + 1) AS HOUR,
    (SELECT COUNT(*) AS COUNT FROM ANIMAL_OUTS WHERE @HOUR = HOUR(DATETIME)) AS COUNT  -- 각 시간대별로 카운트하기 위해 서브쿼리 사용
FROM ANIMAL_OUTS
WHERE @HOUR < 23;            -- while문 조건식처럼 변수 HOUR이 23보다 작을 때만 수행(0~23까지)



-- 년, 월, 성별 별 상품 구매 회원 수 구하기
SELECT YEAR(S.SALES_DATE) AS YEAR, MONTH(S.SALES_DATE) AS MONTH, U.GENDER,
    COUNT(DISTINCT S.USER_ID) AS USERS 
FROM USER_INFO AS U INNER JOIN ONLINE_SALE AS S ON U.USER_ID = S.USER_ID
WHERE U.GENDER IS NOT NULL
GROUP BY YEAR, MONTH, U.GENDER
ORDER BY YEAR ASC, MONTH ASC, U.GENDER ASC;



-- 취소되지 않은 진료 예약 조회하기
SELECT A.APNT_NO, P.PT_NAME, P.PT_NO, D.MCDP_CD, D.DR_NAME, A.APNT_YMD
FROM APPOINTMENT AS A
INNER JOIN PATIENT AS P ON A.PT_NO = P.PT_NO
INNER JOIN DOCTOR AS D ON A.MDDR_ID = D.DR_ID
WHERE A.MCDP_CD = 'CS' AND A.APNT_CNCL_YN = 'N'
    AND DATE_FORMAT(A.APNT_YMD, '%Y-%m-%d') = '2022-04-13'
ORDER BY A.APNT_YMD ASC;



-- 자동차 대여 기록 별 대여 금액 구하기
SELECT H.HISTORY_ID, 
    ROUND(
        C.DAILY_FEE * (DATEDIFF(H.END_DATE, H.START_DATE) + 1)  
        * (1 - IFNULL(P.DISCOUNT_RATE, 0) / 100), 0
    ) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS C
INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H ON C.CAR_ID = H.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P ON C.CAR_TYPE = P.CAR_TYPE 
    AND P.DURATION_TYPE = (
        CASE
            WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 90 THEN '90일 이상'
            WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 30 THEN '30일 이상'
            WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 7 THEN '7일 이상'
            ELSE NULL
        END
    )   -- 자동차 종류와 대여 기간이 모두 일치하는 것에 한해서 LEFT JOIN
WHERE C.CAR_TYPE = '트럭'
GROUP BY H.HISTORY_ID
ORDER BY FEE DESC, H.HISTORY_ID DESC;



-- 언어별 개발자 분류하기
SET @FRONT := (SELECT SUM(CODE) FROM SKILLCODES WHERE CATEGORY LIKE 'FRONT%');
SET @PYTHON := (SELECT CODE FROM SKILLCODES WHERE NAME = 'PYTHON');
SET @C_SHARP := (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#');

SELECT
    CASE
        WHEN (SKILL_CODE & @FRONT) AND SKILL_CODE & @PYTHON THEN 'A'
        WHEN SKILL_CODE & @C_SHARP THEN 'B'
        WHEN SKILL_CODE & @FRONT THEN 'C'
        ELSE NULL
    END AS GRADE, ID, EMAIL
FROM DEVELOPERS
GROUP BY GRADE, ID, EMAIL HAVING GRADE IS NOT NULL  
-- NOT NULL 필터링용 HAVING + GROUP BY 사용(FROM절에 SELECT~FROM DEVELOPERS까지를 서브쿼리로 넣으면 WHERE에서 필터링 가능)
ORDER BY GRADE ASC, ID ASC;